name: Environment Tests

on:
  push:
    branches: [ main ]
    paths:
    - 'app/**/*'
    - 'database/**/*'
    - 'test/**/*'
    - 'start/**/*'
    - 'providers/**/*'
    - 'contracts/**/*'
    - 'config/**/*'
    - 'contracts/**/*'
    - 'commands/**/*'
  pull_request:
    branches: [ main ]
    paths:
    - 'app/**/*'
    - 'database/**/*'
    - 'test/**/*'
    - 'start/**/*'
    - 'providers/**/*'
    - 'contracts/**/*'
    - 'config/**/*'
    - 'contracts/**/*'
    - 'commands/**/*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setting up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nodejs

      - name: Installing API
        run: npm install

      - name: Running tests on API
        run: npm run ci:test

